### ISSUE TITLE
Compile Warning: 'melatonin::internal::CachedShadows' has virtual functions but non-virtual destructor

### ISSUE THREAD

**Issue by JelleBakker** [sudara/melatonin_blur#70]
See title

**Comment by sudara** [comment]
What compiler is this with? (Not seeing this locally) Funny, I removed the explicit dtor because of this other warning when it was in place:

https://github.com/sudara/melatonin_blur/pull/65

**Comment by JelleBakker** [comment]
@sudara adding the following code in CachedShadows makes it compile with zero warnings:


```
CachedShadows (const CachedShadows&) = default;
CachedShadows& operator=(const CachedShadows&) = default;
virtual ~CachedShadows() = default;
```

**Comment by JelleBakker** [comment]
See https://github.com/sudara/melatonin_blur/pull/74
