### ISSUE TITLE
"This wasn't a valid module folder!"

### ISSUE THREAD

**Issue by EXPSTUDIOmo** [sudara/melatonin_blur#71]
Hey,

wanting to use this great library with my Projucer project.
But when I try to add the folder as a user module from a folder (as in the readme) I get the error that this isn't a valid module folder.

Are there any steps to take? 

Using Juce 8.0.1.

Thanks!

**Comment by sudara** [comment]
Hi there — can you confirm the folder you are giving Projucer has the file melatonin_blur.h in it?( I wonder if there’s an extra folder or something if it was downloaded via zip…)

**Comment by EXPSTUDIOmo** [comment]
Hey, thanks for the quick reply.

I figured it out, the folder was named "melatonin_blur-main" after download, after removing the "-main" (so the folder has the same name as melatonin_blur.h I can add it via the Projucer! (maybe important for someone else in the future)

thanks

**Comment by sudara** [comment]
Ok thank you, I will add this to the docs!

**Comment by sudara** [comment]
Added to the new docs here, thanks for reporting: https://melatonin.dev/manuals/melatonin-blur/installation/projucer/#dont-use-git
