### ISSUE TITLE
Please add tags and Releases!

### ISSUE THREAD

**Issue by ImJimmi** [sudara/melatonin_blur#77]
Would be great to add tags and releases so we can point at specific versions of the repo!

We currently pull this in using CPM, targeting `main`, which means we have to fix any breaking changes immediately. If we could point at a specific version, it would give us more control over when we update.

(CPM can also point at specific commit SHAs, but that's a bit gnarly)

**Comment by sudara** [comment]
Heard!

I just push tags for 1.2, 1.3, 1.4.

I revamped the docs yesterday where I explicitly recommend [pointing to a commit](https://melatonin.dev/manuals/melatonin-blur/installation/cmake/#option-2-via-fetchcontent) for now.

Going forward, my plan is to issue tags for patch releases too, but until now I think everyone has just been on main. Baby's growing up!

Oh, and if anything broke, please let me know what it was!

**Comment by ImJimmi** [comment]
> Oh, and if anything broke, please let me know what it was!

They were expected breakages - we were using these copy constructors that are now deleted: https://github.com/sudara/melatonin_blur/commit/2afb7c2062a0f6a026b3a7629f7e141d065cb075#diff-afe5100b68c67ea2cc8f6831549a07742dbd75b8f154f4fa89185d7c65e3fee6R12

Easy to work around, but the tags will help us not have to drop-everything to update in the future, thanks!

**Comment by sudara** [comment]
Ok thanks! Yeah, forget exactly why I had to delete them, I was being yelled at by clang tidy or something.

Hygiene should be improving here and on the inspector — thanks for the motivation!
